config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '',
  	path_names: {sign_in: 'login', sign_up: 'signup'}, 
  	controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  
  namespace :assets do
    :assets
  end

  get '/thanks', to: 'frames#thanks'
  post '/resend_confirmation', to: 'users#resend_confirmation', as: 'resend_confirmation'
  
  resources :users
  patch '/users/:id', to: 'users#update', as: 'user_picture'
  
  post '/pages/add_file', to: 'pages#add_file', as: 'add_file_to_page'  
  resources :pages, param: :page_slug, except: [:index, :show]
  
  resources :categories, param: :title_slug, except: [:index, :show, :update] 
  post '/categories/add_file', to: 'categories#add_file', as: 'add_file_to_category'
  post '/categories/add_user/:title_slug/:user_id', as: 'category_add_user', to: 'categories#add_user'
  post '/categories/change_title', to: 'categories#change_title', as:'update_category_title'
  post '/categories/order_pages', to: 'categories#order_pages', as:'change_pages_order'

 
  resources :teams, param: :team_slug, except: [:index, :show]
  resources :commits, except: [:index, :show, :new]
  resources :invitations

  post '/pages/create_version', to: 'pages#create_version', as: 'new_version'
 
  get '/commits/:page_id/:version_id/new', to: 'commits#new', as: 'new_commit'
 
  post '/teams/remove_member', to: 'teams#remove_member'
  post '/teams/invite_users', to: 'teams#invite_users'
  get '/teams/find', to: 'teams#find'
  get '/teams/added_to_team', to: 'teams#added_to_team', as: 'added_to_team'
 
  get '/bs/:team_slug', to: 'teams#show', as: 'show_team'
  post '/bs/:team_slug', to: 'teams#change_session', as: 'change_session'
 
  get '/api/teams', to: 'teams#index'
  get '/api/categories', to: 'categories#index', as: 'category_api'
  get '/api/pages/:team_slug', to: 'pages#index', as: 'pages_api'
  get '/api/commits', to: 'commits#index', as: 'commits_api'

  get '/bs/:team_slug/:title_slug', to: 'categories#show', as: 'category_display'
  get '/bs/:team_slug/:title_slug/:page_slug', to: 'pages#show', as: 'page_display'
  get '/bs/:team_slug/:title_slug/:page_slug/:version_id', to: 'versions#show', as: 'version_display'
 
  root 'frames#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

    has_attached_file :avatar, styles: { medium: "96x96>", thumb: "64x64>", mini: "32x32>" }, default_url: "missing_:style.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	validates_presence_of :first_name, :last_name
	validates_uniqueness_of :email, :case_sensitive => false

	has_many :cat_users
	has_many :participations
	has_many :categories, through: :cat_users
	has_many :teams, through: :participations

    has_many :invites, :class_name => "Invitation", :foreign_key => 'recipient_id'
    has_many :sent_invites, :class_name => "Invitation", :foreign_key => 'sender_id'

	def full_name
		self.first_name + ' ' + self.last_name
	end

	def first_char
	    self.first_name.chars.first + ' ' + self.last_name.chars.first
	end

	def commits 
  		Commit.where(user_id: self.id).reverse
  	end



end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 
  def new
    @token = params[:invite_token]
    super
  end

  def create
    @token = params[:invite_token]
    if @token != nil
      @newUser = build_resource(sign_up_params)
      @newUser.save
      @token = params[:invite_token]
      team_slug =  Invitation.find_by(token: @token).team_slug 
      team = Team.find_by(slug: team_slug)
      team.users << @newUser 
      expire_data_after_sign_in!
      after_inactive_sign_up_path_for(resource)
    else
      build_resource(sign_up_params)
      resource.save
        yield resource if block_given?
        if resource.persisted?
           expire_data_after_sign_in!
           after_inactive_sign_up_path_for(resource)
        else
           clean_up_passwords resource
           set_minimum_password_length
           respond_with resource
        end
    end
    session[:categories] = []
  end

  def after_inactive_sign_up_path_for(resource)
      session[:user_id] = resource.id
      redirect_to thanks_url
  end


  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :job_title, :location, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :job_title, :location, :avatar)
  end
  
end 

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# skip_before_action :load_categories, only: [:new, :create] #avoids conflict with login process

  def new
    super
  end

  def create

    super

    unless session[:current_team]
      if current_user.teams.size == 0 
       session[:categories] = []
      else
  	    session[:categories] = current_user.categories.where(team_id: current_user.teams.first.id)
  	    session[:current_team] = current_user.teams.first
      end
	  end
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]


	def show
		@users = User.all
		@user = User.find(params[:id])
		@other_categories = Category.all - @user.categories
	end

	def update
	    user = current_user
	    user.update_attribute(:avatar, params[:user][:avatar])
	    redirect_back(fallback_location: root_path)
  	end

  	def resend_confirmation
  		user = User.find_by(id: params[:user_id])
		user.send_confirmation_instructions	
  	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">

  <div class="row">

<!-- Left Column -->
  <%= render "frames/side" %>

<!-- Main body -->

    <div class="eight columns frame main-container">

      <div class="row row-no-border">

        <div class="six columns breadcrumb">
          <p>Profile</p>
        </div>
        <% if current_user == @user %>
        <div class="six columns breadcrumb info--right">
            <%= link_to edit_user_registration_path do%>
            <span class="icons"><%= render :partial => 'svg/edit' %></span>
            <% end %>
        </div>
        <% end %>

      </div>

        <div class="row-no-border">

          <div class="three columns profile-image">
            <% if current_user.avatar %>
              <%= image_tag @user.avatar.url(:medium) %>
            <% end %>
          </div>

          <div class="eight columns main-user-info">
            <h1><%= @user.full_name %> <% if current_user == @user %>(you)<% end %></h1>
            <h3><%= @user.job_title %></h3>
          </div>
        </div>

        <div class="row">

            <ul class="twelve columns user-list-info">
              <li><%= render :partial => 'svg/tack' %><%= @user.location %></li>
              <li><%= render :partial => 'svg/guidelines' %><%= @user.email %></li>
              <li><%= render :partial => 'svg/calendar' %>Joined on <%= @user.created_at.to_time.strftime("%b %d, %Y") %></li>
            </ul>

        </div>

        <div class="row row-no-padding">
          <% if current_user == @user %>
              <label for="user" class="category-title" >Add a new profile picture</label>
              <%= form_for @user, url: user_picture_path, html: { id: 'upload_avatar', multipart: true } do |form| %>
                <%= form.file_field :avatar %>
              <% end %>
              <button class="btn btn--secondary" id="add_avatar">Upload</button>
          <% end %>
        </div>

        <div class="row">

          <div class="user-commits">

            <h5 class="category-title">Latest commits</h5>
            <ul>
            <% @user.commits.each do |c| %>
              <li><b><%= link_to c.title, c.link_to_page %></b><br/>
                  <em><%= c.created_at.to_time.strftime("%b %d, %Y") %></em>
              </li>
            <% end %>
            </ul>

          </div>


          <hr/>

            <p><a href="#" id="addusers-js">Add this user to a category in this team</a></p>

            <div id="list-js" style="display: none">
                <ul>
                <% @other_categories.each do |cat| %>
                 <li> <%= link_to cat.title, category_add_user_path(title_slug: cat.slug, user_id: @user.id), method: :post %> </li>
                <% end %>
                </ul>
            </div>

        </div>

    </div>


      </div>
    </div>
</div>