config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '',
  	path_names: {sign_in: 'login', sign_up: 'signup'}, 
  	controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  
  namespace :assets do
    :assets
  end

  get '/thanks', to: 'frames#thanks'
  post '/resend_confirmation', to: 'users#resend_confirmation', as: 'resend_confirmation'
  
  resources :users
  patch '/users/:id', to: 'users#update', as: 'user_picture'
  
  post '/pages/add_file', to: 'pages#add_file', as: 'add_file_to_page'  
  resources :pages, param: :page_slug, except: [:index, :show]
  
  resources :categories, param: :title_slug, except: [:index, :show, :update] 
  post '/categories/add_file', to: 'categories#add_file', as: 'add_file_to_category'
  post '/categories/add_user/:title_slug/:user_id', as: 'category_add_user', to: 'categories#add_user'
  post '/categories/change_title', to: 'categories#change_title', as:'update_category_title'
  post '/categories/order_pages', to: 'categories#order_pages', as:'change_pages_order'

 
  resources :teams, param: :team_slug, except: [:index, :show]
  resources :commits, except: [:index, :show, :new]
  resources :invitations

  post '/pages/create_version', to: 'pages#create_version', as: 'new_version'
 
  get '/commits/:page_id/:version_id/new', to: 'commits#new', as: 'new_commit'
 
  post '/teams/remove_member', to: 'teams#remove_member'
  post '/teams/invite_users', to: 'teams#invite_users'
  get '/teams/find', to: 'teams#find'
  get '/teams/added_to_team', to: 'teams#added_to_team', as: 'added_to_team'
 
  get '/bs/:team_slug', to: 'teams#show', as: 'show_team'
  post '/bs/:team_slug', to: 'teams#change_session', as: 'change_session'
 
  get '/api/teams', to: 'teams#index'
  get '/api/categories', to: 'categories#index', as: 'category_api'
  get '/api/pages/:team_slug', to: 'pages#index', as: 'pages_api'
  get '/api/commits', to: 'commits#index', as: 'commits_api'

  get '/bs/:team_slug/:title_slug', to: 'categories#show', as: 'category_display'
  get '/bs/:team_slug/:title_slug/:page_slug', to: 'pages#show', as: 'page_display'
  get '/bs/:team_slug/:title_slug/:page_slug/:version_id', to: 'versions#show', as: 'version_display'
 
  root 'frames#index'

end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
before_action :find_teams, except: :thanks
include Find_teams

	def index	
		if session[:current_team]
			@commits = Team.find_by(id: session[:current_team]['id']).commits.reverse
		end
	end

	def thanks
		@user = User.find_by(id: session[:user_id])
	end


end

app/helpers/frames_helper.rb
module FramesHelper
end

app/views/frames/_side.html.erb
<style>
  .prov_selected svg g path {fill: #4158D9;}
  .prov_selected a { color: #4158D9; }
</style>


<div class="three columns main-nav">
     <!-- the following teams menu can probs be changed with Javascript / Ajax Calls -->

    <% if current_user.teams.size != 0 && session[:current_team] %>

      <div class="menu-side">

        <%= render :partial => 'svg/shield' %><span><%= session[:current_team]["name"].capitalize %></span>

        <ul class="dropdown">

              <% current_user.teams.each do |team| %>

                 <li class="category-left list <% if team.name == session[:current_team]["name"] %> prov_selected <% end %>">
                      <%= link_to change_session_path(team.slug),  :method => :post do %>
                        <%= render :partial => 'svg/shield' %>
                        <span><%= team.name.capitalize %></span>
                      <% end %>
                 </li>
              <% end %>
        </ul>

      </div>



          <!-- <hr class="divider"> -->

      <div class="menu-options">

          <div class="list">

            <%= link_to show_team_path(session[:current_team]['slug']) do %>
              <%= render :partial => 'svg/details'%>
              <span>Team details</span>
            <% end %>
          </div>

          <div class="list">

            <%= link_to root_path do %>
              <%= render :partial => 'svg/commit' %>
              <span>Commits</span>
            <% end %>
          </div>

      </div>

      <%= button_to "Create Category", new_category_path, method: :get, class: "btn btn--primary create" %>

      <% if session[:current_team] %>

          <% if session[:categories] == 0 %>

          <p> You don't have any active category in this team yet! </p>

          <% end %>

          <% session[:categories].each do |category| %>

            <div class="category-left list">

              <%= link_to category_display_path(session[:current_team]["slug"], category['slug']) do%>
              <%= render :partial => 'svg/folder' %>
              <span><%= category["title"].capitalize %></span>

              <% end %>

            </div>

          <% end %>

        <% end %>

    <% else %>

        <p>To start using Basicshapes, you must create a Team or find one to join!</p>
          <hr class="divider">
        <%= button_to "Create a Team", new_team_path, method: :get, class: "btn btn--primary create" %>

    <% end %>

</div>

app/views/frames/index.html.erb
<div class="container">

  <div class="row">
<% if user_signed_in? %>


<!-- Left Column -->
  <%= render "frames/side" %>

<!-- Main body -->

    <div class="eight columns">

    <% if @commits %>
      <% @commits.each do |commit| %>

          <div class="frame main-container" id="<%= commit.id %>">

            <div class="row row-no-padding">

              <div class="six columns author-holder">
                <span><%= commit.user.full_name %> in category <%= commit.page.category.title.capitalize %></span>
              </div>

              <div class="six columns breadcrumb info--right">
                  <%= "#{commit.created_at.to_time.strftime("%a, %d %B %Y")}" %>
              </div>

            </div>

            <div class="guidelines-row row-no-padding">
              <!-- Albert, can we change this to h2 or h3? -instead of p? -->
              <p class="title"><%= link_to commit.title, page_display_path(session[:current_team]['slug'], commit.page.category.slug, commit.page.slug) %></p>

            </div>

            <div class="row row-no-padding-top">
              <% if commit.image_file_name %>
                   <%= image_tag commit.image.url, class: "commit__image" %>
              <% end %>
              <%= commit.message.html_safe %>
            </div>

          </div>

      <% end %>
    <% end %>


        <div class="frame main-container">

          <div class="row row-no-padding">

            <div class="six columns author-holder">
              <span><%= session[:current_team][:name].capitalize %> has been created!</span>
            </div>

            <div class="six columns breadcrumb info--right">
                <%= "#{session[:current_team]['created_at'].to_time.strftime("%a, %d %B %Y")}" %>
            </div>

          </div>

          <div class="guidelines-row">

            <p class="title">Welcome to Basic Shapes</p>

          </div>

          <div class="row row-no-padding-top">

            <p class="commit__description">Basicshapes offers a new way to create documentation for any type of business, ofering a seamless collaboration between teams.</p>

            <img src="<%= asset_path('welcome.png')%>" alt="" class="commit__image">

          </div>

        </div>

    </div>

<% else %>


<!-- Main body -->

    <div class="card--center main-container">

      <div class="six columns frame row">

      	<h3>Welcome to Basic Shapes</h3>

        <p class="description description--center">Basic shapes offers a new way to create documentation for design and marketing, ofering a seamless collaboration between teams.</p>

        <div class="actions">

          <%= link_to "Login", new_user_session_path, class: "btn  btn--primary" %>
        	<%= link_to "Signup", new_user_registration_path, class: "btn  btn--secondary btn--separation" %>

        </div>

      </div>

    </div>

<% end %>


  </div>

</div>

app/views/frames/thanks.html.erb
<div class="container">

  <div class="card--center">

    <div class="six columns frame main-container">

        <div class="row">

          <h2>Thanks for signing up</h2>

          <p><%= @user.first_name.capitalize %>, we have sent a confirmation email to your inbox. It could take a couple of minutes to be delivered, thanks for your patience!</p>

          <p><%= button_to "Resend confirmation", resend_confirmation_path(:user_id => @user.id), class: "btn btn--secondary create" %></p>



        </div>

      </div>

   </div>

  </div>