config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '',
  	path_names: {sign_in: 'login', sign_up: 'signup'}, 
  	controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  
  namespace :assets do
    :assets
  end

  get '/thanks', to: 'frames#thanks'
  post '/resend_confirmation', to: 'users#resend_confirmation', as: 'resend_confirmation'
  
  resources :users
  patch '/users/:id', to: 'users#update', as: 'user_picture'
  
  post '/pages/add_file', to: 'pages#add_file', as: 'add_file_to_page'  
  resources :pages, param: :page_slug, except: [:index, :show]
  
  resources :categories, param: :title_slug, except: [:index, :show, :update] 
  post '/categories/add_file', to: 'categories#add_file', as: 'add_file_to_category'
  post '/categories/add_user/:title_slug/:user_id', as: 'category_add_user', to: 'categories#add_user'
  post '/categories/change_title', to: 'categories#change_title', as:'update_category_title'
  post '/categories/order_pages', to: 'categories#order_pages', as:'change_pages_order'

 
  resources :teams, param: :team_slug, except: [:index, :show]
  resources :commits, except: [:index, :show, :new]
  resources :invitations

  post '/pages/create_version', to: 'pages#create_version', as: 'new_version'
 
  get '/commits/:page_id/:version_id/new', to: 'commits#new', as: 'new_commit'
 
  post '/teams/remove_member', to: 'teams#remove_member'
  post '/teams/invite_users', to: 'teams#invite_users'
  get '/teams/find', to: 'teams#find'
  get '/teams/added_to_team', to: 'teams#added_to_team', as: 'added_to_team'
 
  get '/bs/:team_slug', to: 'teams#show', as: 'show_team'
  post '/bs/:team_slug', to: 'teams#change_session', as: 'change_session'
 
  get '/api/teams', to: 'teams#index'
  get '/api/categories', to: 'categories#index', as: 'category_api'
  get '/api/pages/:team_slug', to: 'pages#index', as: 'pages_api'
  get '/api/commits', to: 'commits#index', as: 'commits_api'

  get '/bs/:team_slug/:title_slug', to: 'categories#show', as: 'category_display'
  get '/bs/:team_slug/:title_slug/:page_slug', to: 'pages#show', as: 'page_display'
  get '/bs/:team_slug/:title_slug/:page_slug/:version_id', to: 'versions#show', as: 'version_display'
 
  root 'frames#index'

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :cat_users
	has_many :users, through: :cat_users
	belongs_to :team
	has_many :pages
	has_many :versions, through: :pages
	has_many :documents, as: :documentable


  validates :title, uniqueness: { scope: :team_id,
    message: "this category already exists", case_sensitive: false }

    def sort_pages
    	if self.pages.length > 0
    		self.pages.order(:position)
    	end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :authenticate_user!
before_action :find_teams
include Find_teams
skip_before_action :verify_authenticity_token, only: [:create, :change_title, :order_pages]


	def show
		current_team = Team.find_by(id: session[:current_team]["id"])
		@category = current_team.categories.find_by(slug: params[:title_slug])
		@team_users = current_team.users.select {|user| user.categories.exclude?(@category)}
		session[:current_category] = @category
		unless @category.users.include?(current_user)
			redirect_to('/')
		end
		@files = @category.documents
	end

	def sort
		current_team = Team.find_by(id: session[:current_team]["id"])
		@category = current_team.categories.find_by(slug: params[:title_slug])
		@team_users = current_team.users.select {|user| user.categories.exclude?(@category)}
		session[:current_category] = @category
		unless @category.users.include?(current_user)
			redirect_to('/')
		end
		@files = @category.documents

	end

	def index
   		team = Team.find_by(slug: params[:team_slug])

			# format.html { redirect_to @company, notice: 'Company was successfully updated.' }
   			# format.json {}
      	render json: team.categories
	end

	def new
	end

	def create
		@category = current_user.categories.create!(category_params)
		@category.slug = @category.title.gsub(' ','-')
		@category.save
	    session[:categories] = current_user.categories.where(team_id: session[:current_team]["id"])
		redirect_to('/')
	end

	def destroy
		Category.find_by(slug: params[:title_slug]).delete
	    session[:categories] = current_user.categories.where(team_id: session[:current_team]["id"])
		redirect_to('/')
	end

	def change_title
		category = Category.find_by(slug: params[:title_slug])
		category.update_attribute(:title, params[:title])
		session[:categories] = current_user.categories.where(team_id: session[:current_team]["id"])
		redirect_back(fallback_location: root_path)
	end

	def add_user
		user = User.find_by(id: params[:user_id])
		Category.find_by(slug: params[:title_slug]).users << user
		redirect_back(fallback_location: root_path)
	end

	def toggle_public
		category = Category.find_by(slug: params[:title_slug])
	    if category.is_public? == false
	    	category.update_attribute(:is_public?, true)

	    else
	    	category.update_attribute(:is_public?, false)
	    end
	end

	def add_file
		Category.find_by(slug: session[:current_category][:slug]).documents.create!(document_params)
		redirect_back(fallback_location: root_path)
	end

	def order_pages	
		params[:list].each {|id, pos| Page.find_by(id: id).update_attribute(:position, pos)}
	end


	private

	def category_params
		params.permit(:title, :description, :team_id)
	end


	def document_params
		params.require(:document).permit(:file)
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/new.html.erb
<div class="container">

  <div class="row">

<!-- Left Column -->

  <%= render "frames/side" %>


<!-- Main body -->

    <div class="eight columns frame main-container">

    <div class="create-category-row">
      <h6 class="breadcrumb">Create category</h6>
      <p class="description">Categories are the main sections of your guidelines. In this block you will add pages with the different content you want to show in your guidelines.</p>
    </div>

	  <%= form_tag({}, { :class => "create-category"}) do %>
	  <div>

	    <label for="Category title" >Title</label>
	    <input type="text" name="category[title]" id="category_title"
	      class="form-control">

	  </div>

	  <div>
	    <label for="Category description">Description</label>
	    <textarea type="text" name="category[description]" id="category-description"
	      class="form-control"></textarea>
	  </div>

<!--
    <div>
      <textarea class="froala"></textarea>
    </div>
-->
          <input type="hidden" name="category[team]" id="category_team" value="<%= session[:current_team]['id'] %>">
    <div class="actions">

      <button class="btn btn--primary btn--right btn-category-js">
  	    Save Category
  	  </button>

    </div>

	<% end %>

    </div>

  </div>

</div>

app/views/categories/show.html.erb
<div class="container">

  <div class="row">

<!-- Left Column -->
  <%= render "frames/side" %>

<!-- Main body -->

    <div class="eight columns">

      <div class="frame main-container">

        <div class="row category-header">

          <div class="six columns">
            <h6 class="category-title"><%= @category.title.capitalize %></h6>
            <input type="text" style="display: none" id="category-title" value="<%= @category.title.capitalize %>">
          </div>
          <div class="six columns  info--right">

            <div class="category-title">
              <a href="#" class="edit-category-name disappear_on_edit menu__text">
                <span><%= render :partial => 'svg/edit' %></span>
              </a>
              <%= link_to category_path(@category.slug), method: :delete, class: "menu__text" do%>
                <span><%= render :partial => 'svg/bin' %></span>
              <% end %>
            </div>

            <div class="category-edits">
                <button class="btn btn--primary edit-category-save show_on_edit" style="display: none" data-slug="<%= @category.slug %>">Save changes</button>
            </div>


          </div>

          <div class="twelve columns">

            <p class="categories-description"><%= @category.description %></p>

          </div>

        </div>

        <div class="main-container row--dark">

        <div class="row category-bottom">

          <ul class="pages-list" id="pages-sortable" data-slug="<%= @category.slug %>">

              <span class="card-general add-page">
                <%= link_to new_page_path do%>
                  <div class="mini-card mini-card-trigger">
                    <h2 class="title">Add page</h2>
                    <p class="description">Create new page</p>
                  </div>
                <% end %>
              </span>

            <% if @category.pages.length > 0 %>
                <% @category.sort_pages.each do |page| %>

                  <li class="card-general card-page" data-position="<%= page.position %>" data-id="<%= page.id %>">
                    <%= link_to page_display_path(session[:current_team]['slug'],@category.slug,page.slug) do %>
                      <div class="mini-card">
                        <h2 class="title"><%= page.versions.last.title %></h2>
                        <p class="description page-desc"><%= page.versions.last.description %></p>

                        <div class="mini-card-info">
                          <p class="versions"><%= page.versions.length %> edit<% if page.versions.length > 1%>s<% end%></p>
                          <p class="commits"><%= page.commits.length %> commit<% if page.commits.length > 1%>s<% end%></p>
                        </div>
                      </div>
                    <% end %>
                  </li>

                <% end %>
            <% end %>
          
          </ul>

        </div>

      </div>



        <!-- note: Add amdin authentication here -->

      <div class="row">


        <ul class="users-list">

          <% @category.users.each do |u| %>
          <li class="user">
            <% if u.avatar_file_name  %>
              <%= link_to user_path(u) do %>
                <%= image_tag u.avatar.url(:medium) %>
              <% end %>
            <% else %>
              <%= link_to u.first_char, user_path(u), class: "link" %>
            <% end %>
          </li>
          <% end %>

        </ul>

        <% if @team_users.length > 0 %>

          <div class="new-users">

            <a href="#" id="addusers-js"><span><%= render :partial => 'svg/add' %></span></a>

            <ul class="users">

              <% @team_users.each do |user| %>
               <li> <%= link_to user.full_name, category_add_user_path(title: params[:title], user_id: user.id), method: :post %> </li>
              <% end %>

            </ul>

          </div>

        <% end %>

      </div>

    </div>

      <div  class="frame main-container">

        <div class="row">
          <h4 class="title">Files</h4>
        </div>

            <div class="main-container row--dark" id="#file-list">

              <div class="row category-bottom">
                <ul class="pages-list">

                  <li class="card-general">
                    <%= form_for Document.new, url: add_file_to_category_path, html: { id: 'edit_page', multipart: true } do |form| %>
                        <%= form.file_field :file %>
                      <% end %>
                      <a href="#" class="add-file">
                        <div class="mini-card mini-card-trigger">
                          <h2 class="title">Attach a file</h2>
                        </div>
                      </a>
                  </li>

                  <% @files.each do |file| %>
                      <li class="card-general">
                        <%= link_to file.file.url do %>
                          <div class="mini-card">
                            <h2 class="title"><%= file.file_file_name %></h2>
                            <p class="description" id="page-desc"><%= file.file_content_type %></p>
                          </div>
                        <% end %>
                      </li>
                    <% end %>
                </ul>
              </div>
            </div>
        </div>
    </div>

<!-- Empty Column -->

    <div class="one column empty"> Empty Column </div>


  </div>

</div>

<script type="text/javascript">
  $('.page-desc').each(function(){
    var content = $(this).text()
    if(content.length > 60){
      $(this).text(content.substring(0,52) + '...');
  }});
</script>

<script>
  var el = document.getElementById('pages-sortable');
  var sortable = new Sortable(el, {
    animation: 200,
    onEnd: function() {
      orderPages()
    }
  });
 </script>