config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '',
  	path_names: {sign_in: 'login', sign_up: 'signup'}, 
  	controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  
  namespace :assets do
    :assets
  end

  get '/thanks', to: 'frames#thanks'
  post '/resend_confirmation', to: 'users#resend_confirmation', as: 'resend_confirmation'
  
  resources :users
  patch '/users/:id', to: 'users#update', as: 'user_picture'
  
  post '/pages/add_file', to: 'pages#add_file', as: 'add_file_to_page'  
  resources :pages, param: :page_slug, except: [:index, :show]
  
  resources :categories, param: :title_slug, except: [:index, :show, :update] 
  post '/categories/add_file', to: 'categories#add_file', as: 'add_file_to_category'
  post '/categories/add_user/:title_slug/:user_id', as: 'category_add_user', to: 'categories#add_user'
  post '/categories/change_title', to: 'categories#change_title', as:'update_category_title'
  post '/categories/order_pages', to: 'categories#order_pages', as:'change_pages_order'

 
  resources :teams, param: :team_slug, except: [:index, :show]
  resources :commits, except: [:index, :show, :new]
  resources :invitations

  post '/pages/create_version', to: 'pages#create_version', as: 'new_version'
 
  get '/commits/:page_id/:version_id/new', to: 'commits#new', as: 'new_commit'
 
  post '/teams/remove_member', to: 'teams#remove_member'
  post '/teams/invite_users', to: 'teams#invite_users'
  get '/teams/find', to: 'teams#find'
  get '/teams/added_to_team', to: 'teams#added_to_team', as: 'added_to_team'
 
  get '/bs/:team_slug', to: 'teams#show', as: 'show_team'
  post '/bs/:team_slug', to: 'teams#change_session', as: 'change_session'
 
  get '/api/teams', to: 'teams#index'
  get '/api/categories', to: 'categories#index', as: 'category_api'
  get '/api/pages/:team_slug', to: 'pages#index', as: 'pages_api'
  get '/api/commits', to: 'commits#index', as: 'commits_api'

  get '/bs/:team_slug/:title_slug', to: 'categories#show', as: 'category_display'
  get '/bs/:team_slug/:title_slug/:page_slug', to: 'pages#show', as: 'page_display'
  get '/bs/:team_slug/:title_slug/:page_slug/:version_id', to: 'versions#show', as: 'version_display'
 
  root 'frames#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cat_user.rb
class CatUser < ApplicationRecord
	belongs_to :category
	belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :cat_users
	has_many :users, through: :cat_users
	belongs_to :team
	has_many :pages
	has_many :versions, through: :pages
	has_many :documents, as: :documentable


  validates :title, uniqueness: { scope: :team_id,
    message: "this category already exists", case_sensitive: false }

    def sort_pages
    	if self.pages.length > 0
    		self.pages.order(:position)
    	end
    end

end

app/models/commit.rb
class Commit < ApplicationRecord
belongs_to :user
belongs_to :page
belongs_to :version

    has_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	def link_to_page
		"/bs/#{self.page.category.team.slug}/#{self.page.category.slug}/#{self.page.slug}"
	end


def team
	self.page.category.team
end

end

app/models/document.rb
class Document < ApplicationRecord
	 belongs_to :documentable, polymorphic: true

	 has_attached_file :file
	 validates_attachment :file, presence: true, content_type: {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
before_create :generate_token

      belongs_to :team
      belongs_to :sender, :class_name => 'User'
      belongs_to :recipient, :class_name => 'User'


	def generate_token
	   self.token = Digest::SHA1.hexdigest([self.team_slug, Time.now, rand].join)
	end

end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
belongs_to :category
has_many :versions
has_many :commits
has_many :documents, as: :documentable

 validates_presence_of :slug
 validates :slug, uniqueness: { scope: :category_id,
    message: "this page already exists", case_sensitive: false }


end

app/models/participation.rb
class Participation < ApplicationRecord
	belongs_to :team
	belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :users, through: :participations
	has_many :categories
	has_many :participations
	has_many :pages, through: :categories
	has_many :commits, through: :pages

	has_attached_file :logo, styles: { medium: "160x160>", thumb: "64x64>", mini: "32x32>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/


	validates_presence_of :name
	validates_uniqueness_of :name, message: 'This team name is not available', case_sensitive: false 


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

    has_attached_file :avatar, styles: { medium: "96x96>", thumb: "64x64>", mini: "32x32>" }, default_url: "missing_:style.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	validates_presence_of :first_name, :last_name
	validates_uniqueness_of :email, :case_sensitive => false

	has_many :cat_users
	has_many :participations
	has_many :categories, through: :cat_users
	has_many :teams, through: :participations

    has_many :invites, :class_name => "Invitation", :foreign_key => 'recipient_id'
    has_many :sent_invites, :class_name => "Invitation", :foreign_key => 'sender_id'

	def full_name
		self.first_name + ' ' + self.last_name
	end

	def first_char
	    self.first_name.chars.first + ' ' + self.last_name.chars.first
	end

	def commits 
  		Commit.where(user_id: self.id).reverse
  	end



end

app/models/version.rb
class Version < ApplicationRecord
	belongs_to :page
	belongs_to :user

	validates_presence_of :title
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>Basicshapes</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//rubaxa.github.io/Sortable/Sortable.js"></script>

    <!-- Include external CSS. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">
  
    <!-- Include Editor style. -->
    <link href="<%=asset_path('froala_editor.pkgd.min.css')%>" rel="stylesheet" type="text/css" />
    <link href="<%=asset_path('froala_style.min.css')%>" rel="stylesheet" type="text/css" />

  </head>

  <body>

  <nav class="container-flex top-nav">

    <div class="nav-row">
      <%= render :partial => 'svg/basicshapes-logo' %>
      <% if user_signed_in? %>

        <div class="menu">
          <!-- <div class="image-nav"> -->
            <%= image_tag current_user.avatar.url(:medium), class: "image-nav"%>
          <!-- </div> -->
          <ul class="dropdown">
            <li>
              <%= link_to 'My profile', user_path(current_user) %>
            </li>
            <li>
              <%= link_to "Create team", new_team_path %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: 'delete' do %>
              <span class="red-link">Logout</span>
              <% end %>
            </li>
          </ul>
        </div>

      	<!-- <p>Logged in as <%= current_user.first_name  %>!</p> -->

    	<% else %>

      	<!-- <p>No user is logged in</p> -->

        <div class="">
          <%= link_to "Login", new_user_session_path, class: "btn  btn--primary" %>
        </div>

    	<% end %>
    </div>

  </nav>

    <%= yield %>

    <!-- Include external JS libs. -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script>
    <!-- Include Editor JS files. -->
     <script type="text/javascript" src="<%=asset_path('froala_editor.pkgd.min.js')%>"></script> 

    <!-- Initialize the editor. -->
    <script>
      $(function() {
        $('.froala').froalaEditor({}) });
    </script>

    <script>
      $(function() {
        $('div#froala-editor').froalaEditor({
          toolbarInline: true,
          charCounterCount: false,
          toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'color', 'emoticons', '-', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'indent', 'outdent', '-', 'insertImage', 'insertLink', 'insertFile', 'insertVideo', 'undo', 'redo']
        })
      });
  </script>

  </body>
</html>

app/views/pages/edit.html.erb
edit.html.erb

app/views/pages/new.html.erb
<div class="container">

  <div class="row">

<!-- Left Column -->

  <%= render "frames/side" %>


<!-- Main body -->

    <% if flash[:alert] %>
        <div class="eight columns frame main-container">
          <p><b><%= flash[:alert] %> </b></p>
        </div>
    <% end %>

    <div class="eight columns frame main-container">

      <div class="create-category-row">
        <h6 class="breadcrumb">Create page</h6>
        <p class="description">Pages are the unit of your guides. Create a new page and let your team know by committing it!</p>
      </div>

      <div class="row">
        <%= form_tag({}, { :class => "create-page"}) do %>
      	  <div class="page-field">
      	    <label for="Version title" >Title</label>
      	    <input type="text" id="version_title"
      	      class="form-control">
      	  </div>

      	  <div class="page-field">
      	    <label for="Version description">Description</label>
      	    <textarea type="text" id="version_description"
      	      class="form-control"></textarea>
      	  </div>
                <input type="hidden" id="version_user" value="<%= current_user.id %>">
                <input type="hidden" id="page_category" value="<%= session[:current_category]['id'] %>">
          <div>
            <textarea class="froala" ></textarea>
          </div>

          <div class="actions">

            <button class="btn btn--primary btn--right btn-page-js">
        	    Create Page & Commit
        	  </button>

          </div>

    	  <% end %>
      </div>

    </div>

  </div>

</div>

app/views/pages/show.html.erb
<div class="container">

  <div class="row">


<!-- Left Column -->
  <%= render "frames/side" %>

<!-- Main body -->
    <div class="eight columns">

    <div class="frame main-container">

      <div class="row row-no-padding">
        <div class="nine columns">
          <p>
            <span style="font-weight: 500;">Last change:</span>
            
            <%= @edit_commit_list.last.created_at.to_time.strftime("%a, %d %B %Y") %>
          </p>
        </div>
        <div class="three columns info--right">
          <div id="page-edited">
              <button id="save-page" style="display: none" class="show_on_edit btn--primary btn">Save</button>
          </div>
          <%= link_to page_path(@page.page.slug), method: :delete, class: "menu__text disappear_on_edit" do%>
            <span><%= render :partial => 'svg/bin' %></span>
          <% end %>

        </div>
      </div>

        <div class="row">
          <div class="twelve columns">
            <h1 id="page_title" class="disappear_on_edit title"><%= @page.title %></h1>

            <label style="display: none" class="show_on_edit">Title</label>
            <input type="text" value="<%= @page.title %>" class="show_on_edit" id="version_title" style="display: none">

          </div>
        </div>

        <div class="row row-no-padding-top">
          <div class="twelve columns">
            <p id="page_description" class="disappear_on_edit description"> <%= @page.description %></p>

            <label style="display: none" class="show_on_edit">Description</label>
            <input type="text" value="<%= @page.description %>" class="show_on_edit" id="version_description" style="display: none">
            <input type="hidden" value="<%= params[:page_slug] %>" id="page_slug">
          </div>
        </div>

        <div class="row page-summary row-no-padding-top disappear_on_edit">

          <div class="six columns">
            <div class="basic-info" id="eclink">
              <a id="eclink-link">
                  <span class="number"><%= @page.page.versions.length %></span>
                  <span class="link-icon"><%= render :partial => 'svg/edit' %></span>
              </a>
              <a id="eclink-link">
                <span class="number"><%= @page.page.commits.length %></span>
                <span class="link-icon"><%= render :partial => 'svg/commit' %></span>
              </a>
              <% if @files.length > 0 %>
                <a id="file-link">
                  <span class="number"><%= @files.length %></span>
                  <span class="link-icon"><%= render :partial => 'svg/attach' %></span>
                </a>
              <% end %>
            </div>
        </div>

        <div id="page" class="six columns info--right">
          <button id="edit-page" class="disappear_on_edit btn btn--secondary btn">Edit</button>
          <%= link_to "New commit", new_commit_path(@page.page.id, @page.id), :class => 'disappear_on_edit btn--primary btn create btn--separation' %>
        </div>

        </div>



      <div class="row row-border">
<!-- END PROVISIONAL FILES, COMMIT AND EDIT INFO ON TOP, TO BE STYLED -->

        <input type="hidden" value="<%= current_user.id %>" id="version_user">

        <div class="fr-view" id="page_content">
            <%= @page.content.html_safe %>
        </div>

      </div>

<!-- EDIT AND COMMITS LIST, TO BE STYLED -->

      <div class="row disappear_on_edit">

        <div class="twelve columns">

          <h1 class="changes">Changes</h1>

          <ul id="edit-commit-list">
          <% @edit_commit_list.each do |element| %>
            <% if element.class == Commit %>
              <li class="commit-list" data-id="<%=element.id%>">
                <span><%= render :partial => 'svg/commit' %></span>
                <%= link_to element.title + ", " + element.user.full_name + " on " + element.created_at.to_time.strftime("%a %d %B %Y"),
                root_url + '#' + element.id.to_s %>
              </li>
            <% else %>
              <li class="edit-list">
                <span><%= render :partial => 'svg/edit' %></span>
                   <%= link_to "#{element.created_at.to_time.strftime("%a %d %B %Y")}, #{element.user.full_name}", version_display_path(element.page.category.team.slug, element.page.category.slug, element.page.slug, element.id) %>
                 </li>
            <% end %>
          <% end %>
          </ul>
        </div>
      </div>

    </div>

      <div class="frame main-container disappear_on_edit">

          <div class="row">
            <h4 class="title">Files</h4>
          </div>

              <div class="main-container row--dark" id="#file-list">

                <div class="row category-bottom">
                  <ul class="pages-list">

                    <li class="card-general">
                        <%= form_for Document.new, url: add_file_to_page_path, html: { id: 'edit_page', multipart: true } do |form| %>
                            <%= form.file_field :file %>
                        <% end %>
                        <a href="#" class="add-file">
                          <div class="mini-card mini-card-trigger">
                            <h2 class="title">Attach a file</h2>
                          </div>
                        </a>
                    </li>

                      <% @files.each do |file| %>
                          <li class="card-general">
                            <%= link_to file.file.url do %>
                              <div class="mini-card">
                                <h2 class="title"><%= file.file_file_name %></h2>
                                <p class="description" id="page-desc"><%= file.file_content_type %></p>
                              </div>
                            <% end %>
                          </li>
                        <% end %>
                  </ul>
                </div>
              </div>
      </div>
    </div>

  </div>

</div>

app/views/svg/_add.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
  <g class="hover--svg" id="Guidelines" fill="none" fill-rule="evenodd">
    <path id="Combined-Shape-Copy" fill="#BFBFBF" d="M18 14V9.994C18 8.894 17.105 8 16 8c-1.112 0-2 .893-2 1.994V14H9.994C8.894 14 8 14.895 8 16c0 1.112.893 2 1.994 2H14v4.006c0 1.1.895 1.994 2 1.994 1.112 0 2-.893 2-1.994V18h4.006c1.1 0 1.994-.895 1.994-2 0-1.112-.893-2-1.994-2H18zm-2 18C7.163 32 0 24.837 0 16S7.163 0 16 0s16 7.163 16 16-7.163 16-16 16z"/>
  </g>
</svg>

app/views/svg/_attach.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" class="icons">
  <g fill="none" fill-rule="evenodd">
    <path fill="#F4F5F8" fill-opacity=".01" d="M0 0h16v16H0z"/>
    <path stroke="#BFBFBF" stroke-width="2" d="M12.794 9.936l-1 1.732c-1.25 2.165-3.8 3.58-6.397 2.08C2.8 12.248 2.75 9.333 4 7.168c.507-.862 1.955-3.385 2.5-4.33C7.5 1.106 9.3.99 10.598 1.74c1.3.75 2.098 2.366 1.098 4.098L8.946 10.6c-.43.75-1.4.925-2.05.55-.65-.375-.966-1.33-.548-2.05l2.25-3.896" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
</svg>

app/views/svg/_basicshapes-logo.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<svg width="50px" height="16px" viewBox="0 0 50 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 42 (36781) - http://www.bohemiancoding.com/sketch -->
    <title>Group 10</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <rect id="path-1" x="0" y="0" width="16" height="16" rx="1"></rect>
        <mask id="mask-2" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="16" height="16" fill="white">
            <use xlink:href="#path-1"></use>
        </mask>
        <circle id="path-3" cx="8" cy="8" r="8"></circle>
        <mask id="mask-4" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="16" height="16" fill="white">
            <use xlink:href="#path-3"></use>
        </mask>
        <path d="M7.55274312,0.894513756 C7.79975627,0.40048745 8.19775391,0.395507812 8.44725688,0.894513756 L15.5527431,15.1054862 C15.7997563,15.5995125 15.5553691,16 14.9991283,16 L1.00087166,16 C0.448105505,16 0.197753906,15.6044922 0.447256878,15.1054862 L7.55274312,0.894513756 Z" id="path-5"></path>
        <mask id="mask-6" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="15.2984047" height="15.4778757" fill="white">
            <use xlink:href="#path-5"></use>
        </mask>
    </defs>
    <g id="Design" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Uploads" transform="translate(-42.000000, -19.000000)">
            <g id="Nav">
                <g id="Group-10" transform="translate(42.000000, 19.000000)">
                    <g id="Group-Copy-14">
                        <use id="Rectangle-2" stroke="#000C26" mask="url(#mask-2)" stroke-width="2" fill="#F33040" xlink:href="#path-1"></use>
                        <rect id="Rectangle-5" fill="#DD0112" x="9" y="1" width="6" height="14"></rect>
                    </g>
                    <g id="Group-4-Copy-11" transform="translate(18.000000, 0.000000)">
                        <use id="Oval" stroke="#000C26" mask="url(#mask-4)" stroke-width="2" fill="#FFED99" xlink:href="#path-3"></use>
                        <path d="M1.01897317,7.48066659 C1.00639825,7.65213562 1,7.82532061 1,8 C1,11.8659932 4.13400675,15 8,15 C11.8659932,15 15,11.8659932 15,8 C15,4.13400675 11.8659932,1 8,1 C7.82532061,1 7.65213562,1.00639825 7.48066659,1.01897317 C10.5696304,1.263822 13,3.84808938 13,7 C13,10.3137085 10.3137085,13 7,13 C3.84808938,13 1.263822,10.5696304 1.01897317,7.48066659 Z" id="Combined-Shape" fill="#FFE366"></path>
                    </g>
                    <g id="Group-8-Copy-8" transform="translate(34.000000, 0.000000)">
                        <use id="Triangle-Copy-5" stroke="#000C26" mask="url(#mask-6)" stroke-width="2" fill="#4158D9" xlink:href="#path-5"></use>
                        <polygon id="Path-3-Copy" fill="#142581" points="8 2 8 15 14 15"></polygon>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>

app/views/svg/_bin.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16" class="icons">
  <g class="hover--svg" id="Guidelines" fill="none" fill-rule="evenodd">
    <g id="Group-4" fill="#BFBFBF">
      <path id="Combined-Shape" d="M1 4h12v9.99c0 1.11-.902 2.01-2.01 2.01H3.01C1.9 16 1 15.098 1 13.99V4zM0 1.5C0 .672.675 0 1.498 0h11.004C13.33 0 14 .666 14 1.5V3H0V1.5z"/>
    </g>
  </g>
</svg>

app/views/svg/_calendar.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="icons">
    <!-- Generator: Sketch 42 (36781) - http://www.bohemiancoding.com/sketch -->
    <title>calendar</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g class="hover--svg" id="Guidelines" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M0,1.99406028 C0,0.892771196 0.894513756,0 1.99406028,0 L14.0059397,0 C15.1072288,0 16,0.894513756 16,1.99406028 L16,14.0059397 C16,15.1072288 15.1054862,16 14.0059397,16 L1.99406028,16 C0.892771196,16 0,15.1054862 0,14.0059397 L0,1.99406028 Z M2,2.99077797 L2,7.00922203 C2,7.54902482 2.44358641,8 2.99077797,8 L7.00922203,8 C7.54902482,8 8,7.55641359 8,7.00922203 L8,2.99077797 C8,2.45097518 7.55641359,2 7.00922203,2 L2.99077797,2 C2.45097518,2 2,2.44358641 2,2.99077797 Z" id="calendar" fill="#BFBFBF"></path>
    </g>
</svg>

app/views/svg/_circle.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<svg width="16px" height="16px" viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 42 (36781) - http://www.bohemiancoding.com/sketch -->
    <title>Oval 4</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g class="hover--svg" id="Design" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <circle id="Oval-4" fill="#F33040" cx="8" cy="8" r="8"></circle>
    </g>
</svg>

app/views/svg/_commit.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" class="icons">
  <g fill="none" fill-rule="evenodd">
    <path fill="#F4F5F8" fill-opacity=".01" d="M0 0h16v16H0z"/>
    <path fill="#BFBFBF" d="M7 12.9c-2.282-.463-4-2.48-4-4.9 0-2.42 1.72-4.44 4.006-4.9C7.002 3.062 7 3.026 7 2.99V1.01C7 .45 7.444 0 8 0c.552 0 1 .443 1 1.01v1.98c0 .037-.002.073-.006.11C11.28 3.56 13 5.58 13 8c0 2.42-1.718 4.437-4 4.9v2.09C9 15.55 8.556 16 8 16c-.552 0-1-.443-1-1.01V12.9zM11 8c0-1.657-1.343-3-3-3S5 6.343 5 8s1.343 3 3 3 3-1.343 3-3z"/>
  </g>
</svg>

app/views/svg/_details.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" class="icons">
  <g fill="none" fill-rule="evenodd">
    <circle cx="8" cy="8" r="8" fill="#BFBFBF"/>
    <rect width="2" height="6" x="7" y="7" fill="#F7F7F7" rx="1"/>
    <rect width="2" height="2" x="7" y="3" fill="#F7F7F7" rx="1"/>
  </g>
</svg>

app/views/svg/_edit.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" xmlns:xlink="http://www.w3.org/1999/xlink" class="icons">
  <defs>
    <path id="path-1" d="M0 0h16v16H0z"/>
  </defs>
  <g id="Guidelines" fill="none" fill-rule="evenodd">
    <g id="Group-17-Copy">
      <g id="Group-8">
        <mask id="mask-2" fill="#fff">
          <use xlink:href="#path-1"/>
        </mask>
        <g id="Edit-Copy" fill="#BFBFBF" mask="url(#mask-2)">
          <path id="Combined-Shape" d="M9.344 3.19l3.48 3.483L5.33 14.17c-.787.797-4.98 2.08-5.27 1.788-.29-.29 1.005-4.477 1.787-5.27L9.344 3.19zm1.16-1.16l1.16-1.16c1.162-1.16 2.322-1.16 3.483 0 1.16 1.16 1.16 2.32 0 3.482l-1.16 1.16-3.483-3.48z"/>
        </g>
      </g>
    </g>
  </g>
</svg>